### ISSUE TITLE
(RF)RFC: notifications

### ISSUE THREAD

**Issue by vito** [concourse/rfcs#10]
(TODO)

We had initially planned for notifications and things like GitHub status indiciators to be supported as an explicit interface. These are two very non-resourcey things that are being shoehorned into resources, making pipeline configs verbose and pipeline UIs very noisy (slack notification resources everywhere!).

It may help to see some of the earlier commits to #1 as it had an initial design. We just cut it out to reduce scope.

**Comment by artamonovkirill** [comment]
From #2564:

We are using `on_failure` and `on_success` for Slack notificaitons.
There's quite some noise in our slack notifications at the moment if the build is failing and there are consecutive attempts to fix it.
We practically never use `on_success`, as it will produce even more noise with frequent commits per day.

It would benefit us if there would be two extra options regarding notifications:
* `on_recovery` - notifies when a build is successful and previous finished one was not successful => 'your recent action fixed the build'
* `on_new_failure` - notifies when a build is not successful and previous finished one was successful => 'your recent action broke your build'

**Comment by elgohr** [comment]
Wouldn't it be an option to have something like `on_success_all` and on_failure_all`, which apply to every task but are configured once?

**Comment by pivotal-jwinters** [comment]
Up to this point we've only talked about only being able to emit notifications to external sources (output notifications). It might make sense to allow for notifications to trigger builds as well (input notifications).

We could classify things like `time`, `webhooks`, `manual triggers` as input notifications.

This is especially nice, given that `time` doesn't really fit the mold of what a resource should be. It doesn't have a source of truth, and doesn't really have spaces.

**Comment by ari-becker** [comment]
An idea: Go from:
```yaml
jobs:
- name: my-job
  plan: [...]
```
to:
```yaml
jobs:
- name: my-job
  plan: [...]
  notifications: [...]
```

The idea being that each `notification` is something of a type of a re-usable task (#7). There's common behavior (actually sending the notification to Slack, GitHub, etc.), and there's a common `input` (the build context, which would say whether the build succeeded or not, where it failed if it failed, etc.) - what's actually up to the user is to decide on how the build context schema gets translated (or not, in which case, no notification will be sent for the specific build context to that specific notification) into the resource-specific schema which the notification resource takes as input and uses to send the notification.

This approach has the following benefits:
* No copy-paste of notifications in multiple places along the pipeline
* No UI cluttering - notification resources could be drawn separately, according to the last notification fired
* No pipeline cluttering via copy-pasting 99% the same notification across `on_error`, `on_abort`, `on_failure`, because the build context schema would just represent some `status: failure` etc. in text
* Preserves flexibility on the part of notification resource authors to define their own input schemas

The downside is having to figure out the translation mechanism - whether that's Go templating or scripting (which needs to be cloned from source control, and then, how do you notify a cloning failure?), I'd leave up for more brainstorming.

**Comment by vito** [comment]
@ari-becker Looks like I don't have any details in the RFC yet (https://github.com/concourse/rfcs/pull/28), but the current plan is to be able to annotate an artifact resource with a notification resource which will automatically fire based on state changes to builds that run with the resource. This would work by passing the artifact resource's config fragment (i.e. version, `ref: abcdef`, see #24) to the notification resource, and having some standard way to convey the build status to the resource. There's also some consideration to be made for things like 'build went from red to green' (fixed) or 'build went from green to red' (broken).
