### ISSUE TITLE
Are partial implementations (not implementing all interfaces) for resources a bad thing?

### ISSUE THREAD

**Issue by itsdalmo** [concourse/rfcs#4]
RFC https://github.com/concourse/rfcs/pull/1 has a goal that is stated as:
>Introduce a more airtight "versioned artifacts" interface, tightening up loopholes in today's resource API to ensure that resources are pointing at an external source of truth and cannot be partially implemented or hacky.

Personally, I'm not sure why partial implementations (understood as not implementing all interfaces) for resources is considered a bad thing?

To elaborate on the partial implementations; In order to learn how to write Concourse resources, I started by rewriting a couple of existing ones in Go: 
- [ami-resource](https://github.com/itsdalmo/ami-resource) and a [packer-resource](https://github.com/itsdalmo/packer-resource) which only implements `check` and `get` because it cannot create AMI's itself.
- [packer-resource](https://github.com/itsdalmo/packer-resource) which implements `get` and `put`, since it cannot discover new AMI's that were not produced via `put`.

With Concourse, I get that they should ideally be baked into one resource that implements all interfaces. However, in reality there is a complete disconnect between the filters set up to discover a new AMI, and the Packer template that is passed into the packer resource - so to me it makes complete sense to keep them as two separate (but incomplete) resources, and I believe an attempt to rewrite them into one resource would result in a lesser version of both (functionally).

I.e., I guess what I'm wondering is whether this is the type of partial implementations you want to get rid of? And in which case, why? 😄

**Comment by vito** [comment]
(Moving my reply here, thanks for opening the issue!)

I don't necessarily have a problem with partial implementations as a rule, only implementations that don't really follow the intended design of resources. Partial implementations usually point to some misuse of the resource design. This often ends up with awkward limitations and/or surprising behavior. Usually it points to some pattern that Concourse doesn't represent very well.

concourse/rfc#1 is for discovering those missing ideas and designing for them properly, so at least initially I'd prefer to explore those, since partial implementations are already the "de facto" and I've observed many drawbacks over the years.

Resources, more specifically "artifact resources" per concourse/rfc#1, are meant to have the following properties:

* They have some external source of truth. If you destroy the pipeline and re-create it, all the versions should be recoverable, and their data re-fetchable. If there's no `check`, this can't really be true.
* Their artifacts are versioned, so that concurrent builds can be working with different versions, and downstream jobs can know when there are new versions to run against.
* Versions must have a deterministic order to them, derived only from their configuration. Without this there's no way to know when new versions appear from `check`, or what the latest version is.
* A resource's config + space + version, when passed to `get`, must *always* yield the same data. In addition, `get` should have zero side-effects. Without this property, caching cannot be trusted.
* The `put` command should be idempotent, and always result in the same side-effect, and ideally the same version when given the same inputs. Otherwise re-triggering failed builds is unsafe.

I can't really give a great explanation for these other than they're "Concoursey". When you're using a resource that fits all these properties, using it just feels more natural. Pipelines make these assumptions in all sorts of subtle ways. Resources are everything to Concourse - they're the wind beneath every pipeline's wings. When they're misused, there's turbulence.

The only resources I know of that are "partial" while satisfying all of these points are ones that don't implement `put`. That's a pretty common case for when they're monitoring a read-only source like RSS. I don't think that goes against the design - it's just a read-only interaction.

Most other partial resources are really representing something other than a versioned artifact. They may be notifications, single-state objects, or even better off just as a task. We've had the same resource interface for years, and it had too many holes in its design. This allowed people to shoehorn non-resourcey things into the resource interface, thus delaying the introduction of new features or abstractions that better represent what the user is trying to do. This is why I consider it a local maxima.

**Comment by vito** [comment]
@itsdalmo Yep, exactly. Rather than having a single rather open-ended API, we'll identify and define proper interfaces (without loopholes) as we need them. With v2 we're initially focusing on the artifact use case, and will force ourselves to come up with something nicer for notifications and other patterns, since they intentionally don't fit into the artifact API.

**Comment by itsdalmo** [comment]
Partial implementations _are_ bad 😂

**Comment by vito** [comment]
Agreed! :P
